### ISSUE TITLE
botkit - Botframework as app service in azure , not working

### ISSUE THREAD

**Issue by saikiran1993** [howdyai/botkit#1003]
I have developed a bot using bot kit-bot framework. It is running locally with ngrok / local tunnel with the webhook endpoint.As endpoint changes, every time bot is restarted  So I want to host this bot on Azure as app service. I have deployed bot through GitHub as continuous deployment. Bot is not running and error in sending messages on ms-bot test, could you help me how to make it run as azure app service 
 Can you please help me how to publish bot kit - Botframework as app service on Azure and what could be endpoint URL. As I wanted to run bot on skype.. It is easy to deploy botbuilder node js bot on azure

------------------------------------------------------
**app.js**

var Botkit = require('botkit');
var controller = Botkit.botframeworkbot({
});

var bot = controller.spawn({
appId: '5e1a87ee-9253-4c11-8a78-62513f5bdd9d',
appPassword: 'W0bS9NAJHQo9aXbbqD4sW4w'
});

// if you are already using Express, you can use your own server instance...
// see "Use BotKit with an Express web server"
controller.setupWebserver(process.env.port||3000,function(err,webserver) {
controller.createWebhookEndpoints(controller.webserver, bot, function() {
console.log('This bot is online!!!');
});
});

// user said hello
controller.hears(['hello'], 'message_received', function(bot, message) {

bot.reply(message, 'Hey there.');
});

controller.hears(['cookies'], 'message_received', function(bot, message) {

bot.startConversation(message, function(err, convo) {

    convo.say('Did someone say cookies!?!!');
    convo.ask('What is your favorite type of cookie?', function(response, convo) {
        convo.say('Golly, I love ' + response.text + ' too!!!');
        convo.next();
    });
});
});
------------------------------------------------------------------------------------------------------
**package.json**
{
"name": "botkitresetbot",
"version": "1.0.0",
"description": "",
"main": "app.js",
"scripts": {
"test": "echo "Error: no test specified" && exit 1"
},
"author": "",
"license": "ISC",
"dependencies": {
"botkit": "^0.5.8",
"restify":"^5.2.0",
"botbuilder":"^3.9.1",
"os":"0.1.1",
"command-line-args":"4.0.7",

}
}

**Comment by ouadie-lahdioui** [comment]
What is the error ? can you share some logs ?

**Comment by saikiran1993** [comment]
Can you please help me how to publish botkit - Botframework as app service on Azure and what could be endpoint url

**Comment by saikiran1993** [comment]
**app.js**

var Botkit = require('botkit');
var controller = Botkit.botframeworkbot({
});

var bot = controller.spawn({
    appId: '5e1a87ee-9253-4c11-8a78-62513f5bdd9d',
    appPassword: 'W0bS9NAJHQo9aXbbqD4sW4w'
});

// if you are already using Express, you can use your own server instance...
// see "Use BotKit with an Express web server"
controller.setupWebserver(process.env.port,function(err,webserver) {
  controller.createWebhookEndpoints(controller.webserver, bot, function() {
      console.log('This bot is online!!!');
  });
});

// user said hello
controller.hears(['hello'], 'message_received', function(bot, message) {

    bot.reply(message, 'Hey there.');

});

controller.hears(['cookies'], 'message_received', function(bot, message) {

    bot.startConversation(message, function(err, convo) {

        convo.say('Did someone say cookies!?!!');
        convo.ask('What is your favorite type of cookie?', function(response, convo) {
            convo.say('Golly, I love ' + response.text + ' too!!!');
            convo.next();
        });
    });
});

**package.json**
{
  "name": "botkitresetbot",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "botkit": "^0.5.8",
    "restify":"^5.2.0",
    "botbuilder":"^3.9.1",
    "os":"0.1.1",
    "command-line-args":"4.0.7",

  }
}

**Comment by saikiran1993** [comment]
Messages are not sent

**Comment by saikiran1993** [comment]
yes

**Comment by peterswimm** [comment]
And is your azure based endpoint reachable? It will likely be something like <app_name>.azurewebsites.net

**Comment by saikiran1993** [comment]
nope even i tried https://<app_name>.azurewebsites.net/botframework/receive

**Comment by peterswimm** [comment]
Ok sounds like you are using the correct example app:
https://github.com/howdyai/botkit/blob/master/examples/botframework_bot.js

What happens when you run that with:
debug:true

Please post any console errors.

**Comment by saikiran1993** [comment]
Ya I am using same example. On my local machine it is running with no problems but as i hosted on azure messages are not sent an i find some http errors

**Comment by peterswimm** [comment]
Please share what errors you encounter.

**Comment by saikiran1993** [comment]
Please suggest me steps to deploy as it's not the problem in azure I think its problem in bundling and packaging when I deploy  since it is working fine locally

**Comment by saikiran1993** [comment]
Application has thrown an uncaught exception and is terminated:

SyntaxError: Unexpected token ILLEGAL

    at Module._compile (module.js:434:25)

    at Object..js (module.js:464:10)

    at Module.load (module.js:353:31)

    at Function._load (module.js:311:12)

    at Module.require (module.js:359:17)

    at require (module.js:375:17)

    at Object.<anonymous> (D:\home\site\wwwroot\lib\Botkit.js:2:16)

    at Module._compile (module.js:446:26)

    at Object..js (module.js:464:10)

    at Module.load (module.js:353:31)

Application has thrown an uncaught exception and is terminated:

SyntaxError: Unexpected token ILLEGAL

    at Module._compile (module.js:434:25)

    at Object..js (module.js:464:10)

    at Module.load (module.js:353:31)

    at Function._load (module.js:311:12)

    at Module.require (module.js:359:17)

    at require (module.js:375:17)

    at Object.<anonymous> (D:\home\site\wwwroot\lib\Botkit.js:2:16)

    at Module._compile (module.js:446:26)

    at Object..js (module.js:464:10)

    at Module.load (module.js:353:31)

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml">

**Comment by saikiran1993** [comment]
my bot is running on app service now but it is not responding

**Comment by peterswimm** [comment]
Sorry I do not have a lot of experience deploying on Azure, I would check that it can indeed reach the outside web, and that the endpoint url is setup in bot framework correctly.

**Comment by saikiran1993** [comment]
It started working now ....with pipe thank you

**Comment by peterswimm** [comment]
Good news!

**Comment by sahootanmay** [comment]
i am unable to publish my app from visual studio for bot

**Comment by peterswimm** [comment]
@sahootanmay sorry this repo isn't the best place for visual studio support.

**Comment by thaoth58** [comment]
Hi @saikiran1993 
How can you fix this :D

**Comment by gijsclaes** [comment]
I am having the exact same problem, how did you fix this? @saikiran1993 @thaoth58
