### ISSUE TITLE
Facebook.js doesn't understand beta `standyby` message.

### ISSUE THREAD

**Issue by Yulgana33** [howdyai/botkit#1012]
On initialising a new conversation with botkit I get the following error:

TypeError: Cannot read property 'length' of undefined
    at Object.Facebookbot.facebook_botkit.handleWebhookPayload (/app/node_modules/botkit/lib/Facebook.js:266:59)
at /app/components/routes/incoming_webhooks.js:18:20
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/app/node_modules/serve-static/index.js:75:16)

**Comment by Yulgana33** [comment]
{
   'id': '267342063756729',
   'time': 1503131104641,
   'standby': [ [Object] ] 
}

**Comment by ouadie-lahdioui** [comment]
Hi,

Issue already reported here #962 and here #990, it will be fixed by the PR #978
