### ISSUE TITLE
botkit module giving error "TypeError: Cannot read property 'length' of undefined "

### ISSUE THREAD

**Issue by rosmijarvis** [howdyai/botkit#1074]
Hi,

I recently installed the latest version of botkit module. 
Below is the json which the bot sends as a response to something which user said,

{
                    "recipient": {
                        "id": psNumber
                    },
                    "message": {
                        "attachment": {
                            "type": "template",
                            "payload": {
                                "template_type": "list",
                                "elements": [
									{
                                    "title": "Stationary",
                                    "image_url": "http://apobmms.cgg.gov.in/images/helpdesk.png",
                                    "subtitle": "Kindly choose the right item."
                                },
								{
                                        "title": 'Pencil box',
                                        "subtitle": 'Product:Pencil box',
                                        "buttons": [{
                                            "title": 'Product:Pencil box',
                                            "type": "postback",
                                            "payload":'Product:Pencil box'
                                        }]
                                },
								{
                                        "title": 'Eraser',
                                        "subtitle": 'Product:Eraser',
                                        "buttons": [{
                                            "title": 'Product:Eraser',
                                            "type": "postback",
                                            "payload":'Product:Eraser'
                                        }]
                                }
								
								]
                            }
                        }
                    }
                }
Later when I click on one those buttons I get the below error.

**TypeError: Cannot read property 'length' of undefined**   
   at Object.facebook_botkit.handleWebhookPayload (d:\POCs\IBM_Insurance_POC\AIPlatformV4_2\Channels\node_modules\botkit\lib\Facebook.js:278:63)
    at d:\POCs\IBM_Insurance_POC\AIPlatformV4_2\Channels\node_modules\botkit\lib\Facebook.js:250:29
    at Layer.handle [as handle_request] (d:\POCs\IBM_Insurance_POC\AIPlatformV4_2\Channels\node_modules\botkit\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\POCs\IBM_Insurance_POC\AIPlatformV4_2\Channels\node_modules\botkit\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (d:\POCs\IBM_Insurance_POC\AIPlatformV4_2\Channels\node_modules\botkit\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\POCs\IBM_Insurance_POC\AIPlatformV4_2\Channels\node_modules\botkit\node_modules\express\lib\router\layer.js:95:5)
    at d:\POCs\IBM_Insurance_POC\AIPlatformV4_2\Channels\node_modules\botkit\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (d:\POCs\IBM_Insurance_POC\AIPlatformV4_2\Channels\node_modules\botkit\node_modules\express\lib\router\index.js:335:12)
    at next (d:\POCs\IBM_Insurance_POC\AIPlatformV4_2\Channels\node_modules\botkit\node_modules\express\lib\router\index.js:275:10)

**The same thing when I do with the older version of botkit module it works fine!**
Can someone provide a solution to this?

**Comment by jonchurch** [comment]
What version of Node are you running?
