### ISSUE TITLE
MS Teams crashes on invoke event

### ISSUE THREAD

**Issue by mbouclas** [howdyai/botkit#1201]
Trying to follow the example on invoke type buttons, i setup a button like so:
```
reply =
  {
    text: 'This message has an invoke button',
    attachments: [
      {
         "contentType": "application/vnd.microsoft.card.hero",
         "content": {
           // other card fields here, see above
           // title: '...',
           // subtitle: '...',
           // ...
           "buttons": [
             {
               "type": "invoke",
               "title": "Click Me",
               "value": "{\"action\":\"click\"}"
             }
           ]
      }
    ]
  };

  bot.reply(messge, reply);
```
and registering a controller as the example suggests
```
controller.on('invoke', function(bot, message) {

  // value is a user-defined object
  var value = message.value;

  // send a reply to the user
  bot.reply(messge,'You clicked a button!');

});
```

shows up the button properly. When clicking the button though, botkit crashes with the following error
```
TypeError: this.onInvokeHandler is not a function
    at ChatConnector.onDispatchEvents /work/prj/node_modules/botbuilder/lib/bots/ChatConnector.js:440:22)
    at ChatConnector.dispatch /work/prj/node_modules/botbuilder/lib/bots/ChatConnector.js:452:18)
    at /work/prj/node_modules/botbuilder/lib/bots/ChatConnector.js:140:27
    at OpenIdMetadata.getKey /work/prj/node_modules/botbuilder/lib/bots/OpenIdMetadata.js:26:13)
    at ChatConnector.verifyBotFramework /work/prj/node_modules/botbuilder/lib/bots/ChatConnector.js:114:28)
    at /work/prj/node_modules/botbuilder/lib/bots/ChatConnector.js:44:23
    at Layer.handle [as handle_request] /work/prj/node_modules/express/lib/router/layer.js:95:5)
    at next /work/prj/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch /work/prj/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] /work/prj/node_modules/express/lib/router/layer.js:95:5)
    at /work/prj/node_modules/express/lib/router/index.js:281:22
    at Function.process_params /work/prj/node_modules/express/lib/router/index.js:335:12)
    at next /work/prj/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser /work/prj/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] /work/prj/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix /work/prj/node_modules/express/lib/router/index.js:317:13)
```

Am i missing something here?

**Comment by auberryberry** [comment]
Looks like you're using BotBuilder and not BotKit? could be asking for help in the wrong place? @mbouclas
