### ISSUE TITLE
not able to run slackbutton_bot_interactivemsg.js(help)

### ISSUE THREAD

**Issue by ManjunathanR** [howdyai/botkit#1219]
Not able to run  slackbutton_bot_interactivemsg.js

getting the below error msg.

Error: Cannot find module 'C:\Users\i316454\Desktop\Slack bot project\botkit-master\examples\slackbutton_bot_interactivemsg.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by ManjunathanR** [comment]
I am using both slack bot starter kit and botkit master and installed both on node.js

npmstart does not work in botkit master.

**Comment by ManjunathanR** [comment]
do we need to paste the clientid, clientkey from .env to slackbutton_bot_interactivemsg.js to run it

**Comment by ManjunathanR** [comment]
if we want to create the above Slack Button application bot what is the Event Subscriptions Request URL and Redirect URLs for oauth please advise.

**Comment by ManjunathanR** [comment]
# RUN THE APP:
  Create a Slack app. Make sure to configure the bot user!
    -> https://api.slack.com/applications/new
    -> Add the Redirect URI: http://localhost:3000/oauth

Please explain how to do this bot which is i was looking and perfect one please help

**Comment by peterswimm** [comment]
Please search our documentation before opening issues, most the answer you need will be found there:

https://github.com/howdyai/botkit/blob/master/docs/provisioning/slack-events-api.md
