### ISSUE TITLE
MS Teams findConversation api typo error - ReferenceError: botkti is not defined

### ISSUE THREAD

**Issue by narenderpal** [howdyai/botkit#1222]
```
An error occured in the categorize middleware:  ReferenceError: botkti is not defined
    at Object.bot.findConversation (/home/org/workspace/sample-bot/node_modules/botkit/lib/Teams.js:182:23)
    at /home/org/workspace/sample-bot/node_modules/botkit/lib/CoreBot.js:132:21
```

https://github.com/howdyai/botkit/blob/master/lib/Teams.js#L182

<img width="920" alt="screen shot 2018-01-23 at 3 52 51 pm" src="https://user-images.githubusercontent.com/10447261/35271990-ba3e98a8-0059-11e8-81f9-ce223082704c.png">

**Comment by benbrown** [comment]
Yikes! Thanks
