### ISSUE TITLE
TypeError: Cannot set property 'channel' of undefined bot.reply

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1246]
I am send a message from message_received trigger using this code of mine : 
```
if(/^(\w+) (\w+)$/i.test(message.text)){
                    goOn(message.user,null,RegExp.$1,RegExp.$2,i18n.t).then(function(messageToSend){
                        bot.reply(message,messageToSend);
                    }).catch(function(e){
                        consoleLog('message received votesign');
                        consoleLog(e);
                    });
                }
``` 

But it giving me this error : 
> info: TypeError: Cannot set property 'channel' of undefined
>     at Object.bot.reply (E:\Documents\kaka\coco\voila\node_modules\botkit\lib\Facebook.js:216:25)
>     at E:\Documents\kaka\coco\voila\bot.js:133:29
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by MagSag** [comment]
I have find where the problem is, the **messageToSend** variable value was _**undefined**_ that's why.
