### ISSUE TITLE
Error in Botkit Studio Stats: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by nottinhill** [howdyai/botkit#1259]
```
Error in Botkit Studio Stats: SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (/opt/source/node_modules/botkit/lib/Studio.js:512:33)
    at Request.self.callback (/opt/source/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/source/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/source/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

```

Any ideas what this could be? It wasnt on our servers last week.

**Comment by peterswimm** [comment]
Our Hosting provider was having some issues, which was causing trouble in your Application. We made some adjustments to our system, and their work has completed so you should not be seeing these errors going forward.
