### ISSUE TITLE
Slack's users.lookupByEmail API is not available

### ISSUE THREAD

**Issue by piglovesyou** [howdyai/botkit#1278]
[The doc](https://github.com/howdyai/botkit/blob/master/docs/readme-slack.md#using-the-slack-web-api) says "it may call [any of these methods](https://api.slack.com/methods)" but [users.lookupByEmail](https://api.slack.com/methods/users.lookupByEmail) is not available.

How can I report this or where I can see progress of API support?

**Comment by peterswimm** [comment]
How are you trying to call it? Can you post what code you tried that is not working?

**Comment by piglovesyou** [comment]
Thank you, I did it just in a console on IntelliJ break point. I'll try it in a code later.

**Comment by piglovesyou** [comment]
@peterswimm  It is something like this
```javascript
import Botkit from 'botkit';

const controller = Botkit.slackbot({
  debug: true,
  scopes: ['bot', 'users:read.email'],
});

const bot = controller.spawn({
  token: process.env.token
}).startRTM();

controller.hears('hello', ['direct_message', 'direct_mention', 'mention'], (bot, message: Message) => {
  bot.api.users.lookupByEmail({email: 'xxx@yyy.com'}, function (err, response) {
    console.log(response);
  });
});
```
And I got this
```
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO W8TUH1J6Q C9L7K86DV direct_mention
debug: I HEARD [ 'hello' ]
An error occured in the categorize middleware:  TypeError: bot.api.users.lookupByEmail is not a function
    at controller.hears (/xxx/memphis/src/main.js:14:17)
    at /xxx/memphis/node_modules/botkit/lib/CoreBot.js:1251:32
    at next (/xxx/memphis/node_modules/ware/lib/index.js:82:27)
    at Ware.run (/xxx/memphis/node_modules/ware/lib/index.js:88:3)
    at Object.<anonymous> (/xxx/memphis/node_modules/botkit/lib/CoreBot.js:1250:49)
```

**Comment by shishirsharma** [comment]
@piglovesyou Please open this as a PR.
