### ISSUE TITLE
Unable to run botkit server after delete a skill module file!

### ISSUE THREAD

**Issue by softmastx** [howdyai/botkit#1477]
MacBook-Pro:botkitweb mycom$ node .
Initializing Botkit v0.6.16
info: ** Using simple storage. Saving data to /Users/mycom/BOTKIT/botkitweb/.data/db/
/Users/mycom/BOTKIT/botkitweb/skills/.DS_Store:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/mycom/BOTKIT/botkitweb/bot.js:69:3
    at Array.forEach (native)

This error happen after I deleted a skill module file downloaded from Botkit Studio!

Thanks

**Comment by softmastx** [comment]
**This issue has been solved by recursively remove .DS_Store**
Open up Terminal
In the command line, cd to/your/directory
Finally, in the command line, type: **`find . -name '.DS_Store' -type f -delete`**. Press enter.
