### ISSUE TITLE
ReferenceError: botkit is not defined

### ISSUE THREAD

**Issue by iworkforthem** [howdyai/botkit#1488]
Initializing Botkit v0.6.17
info: ** Using simple storage. Saving data to /Users/waimun/Documents/test/botkit/.data/db/
/Users/waimun/Documents/test/botkit/node_modules/botkit/lib/Web.js:68
        botkit.wss = wss;
        ^

ReferenceError: botkit is not defined
    at Object.WebBot.controller.openSocketServer (/Users/waimun/Documents/test/botkit/node_modules/botkit/lib/Web.js:68:9)
    at Object.<anonymous> (/Users/waimun/Documents/test/botkit/bot.js:61:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by iworkforthem** [comment]
@benbrown this line was added in the a9dd150e0c4e9106d802849c064fd83ebd477c2c commit. Is it required? 

botkit.wss = wss;

**Comment by benbrown** [comment]
Oops! I am publishing another version that will fix this. Thank you for the report.

**Comment by benbrown** [comment]
Fixed in 0.6.18, now published to npm.

Thanks again.
