### ISSUE TITLE
 Unexpected token function

### ISSUE THREAD

**Issue by aaadipop** [howdyai/botkit#1540]
Steps to reproduce:
git clone https://github.com/howdyai/botkit.git
cd botkit/
npm install -g botkit
botkit new

Error:

/usr/local/lib/node_modules/botkit/bin/cli.js:129
async function buildBotkit(options) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

System 
OSX 10.12.16
node v6.11.2

**Comment by kobarasukimaro** [comment]
Hello.

I think sync function is not supported by node v6.11.2.
Nodejs supports async function from v7.6 or later.

Thank you.

**Comment by benbrown** [comment]
That's right -@aaadipop you should update your Node to the latest stable version.
