### ISSUE TITLE
botkit new my_project -p web is showing error to create new botkit application

### ISSUE THREAD

**Issue by redasari** [howdyai/botkit#1611]
$ npm install -g botkit
C:\Users\redasari\AppData\Roaming\npm\botkit -> C:\Users\redasari\AppData\Roaming\npm\node_modules\botkit\bin\cli.js
+ botkit@0.7.4
added 430 packages from 361 contributors in 247.361s

$ botkit new my_project -p web
C:\Users\redasari\AppData\Roaming\npm\node_modules\botkit\bin\cli.js:119
async function buildBotkit(options) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by benbrown** [comment]
Looks like you need to upgrade your version of Node.

**Comment by benbrown** [comment]
Any luck, @redasari?
