### ISSUE TITLE
Make bot use text in DM to send a message in channel

### ISSUE THREAD

**Issue by WisseHesNL** [howdyai/botkit#1624]
Hi all, I want to make a announcements bot. How? I send a dm to my bot saying `announce <my announcement>`, but how do I make my bot use `<my announcement>` and put it in a variable so I can make it send a message in the announcements channel?

### What was the result you received?
none, I can't find anything on this
### What did you expect?
To send a announcement when I send a dm with `announce`
### Screenshots and animated GIFs
none
### Context:
I'm the owner of the slack workspace of our class and I want to make a bot to make announcements on my `#announcements` channel
- Botkit version: 0.7.4
- Messaging Platform: slack
- Node version: v8.9.3
- Os: MacOS 10.13.6
- Any other relevant information: nope

Thanks!

**Comment by casz** [comment]
My example is a little bit more complex with some interactivity :sweat_smile:

I prefer to stringify the value or explore other ways of saving incomplete answers, but it works with comma separation for now :sweat: 

Being able to choose a channel and who is posting.
```
module.exports = (controller) => {
  controller.hears(
    /say announcement "(.+?)"/is,
    'direct_mention',
    (bot, message) => {
      console.log(message)
      message.match.shift() // skip full match
      const text = message.match.shift()
      const reply = {
        text,
        attachments: [
          {
            text: 'Which channel should I send to?',
            fallback: 'Which channel should I send to?',
            callback_id: 'announcement_interactive_channel',
            actions: [
              {
                name: 'channels_list',
                text: 'Which',
                type: 'select',
                data_source: 'channels',
              },
            ],
          },
        ],
      }
      bot.reply(message, reply)
    }
  )
  controller.on(
    'interactive_message_callback',
    async (bot, message) => {
      if (message.callback_id === 'announcement_interactive_channel') {
        console.dir(message, { depth: null })

        const reply = {
          text: message.original_message.text,
          attachments: [
            {
              text: 'Who should I send as?',
              fallback: 'Who should I send as?',
              callback_id: 'announcement_interactive_whom',
              actions: [
                {
                  name: 'send_as_list',
                  text: 'Whom?',
                  type: 'select',
                  options: [
                    {
                      text: 'The Clinic',
                      value: `${message.text},The Clinic`,
                    },
                    {
                      text: '3Shape',
                      value: `${message.text},3Shape`,
                    },
                  ],
                },
              ],
            },
          ],
        }
        bot.replyInteractive(message, reply)
      } else if (message.callback_id === 'announcement_interactive_whom') {
        console.dir(message, { depth: null })
        const [channel, username] = message.text.split(',')
        const emoji = {
          'The Clinic': ':theclinic_logo:',
          '3Shape': ':3shape:',
        }
        const say = {
          text: message.original_message.text,
          icon_emoji: emoji[username],
          username,
          channel,
        }
        bot.say(say, (err) => {
          if (err) {
            bot.replyInteractive(
              message,
              `Failed sent message to <#${channel}>`
            )
          } else {
            bot.replyInteractive(
              message,
              `Successfully sent message to <#${channel}>`
            )
          }
        })
      }
    }
  )
}
```

**Comment by WisseHesNL** [comment]
I tried to run your code, but it fails =(
error:
```
MBP-van-Wisse:node wissehes$ node index.js 
/Path/To/My/Code/index.js:24
    /say announcement "(.+?)"/is,
    ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

config:
```
var Botkit = require('botkit');

var controller = Botkit.slackbot();

var bot = controller.spawn({

  token: "My-Token"

})

bot.startRTM(function(err,bot,payload) {

  if (err) {

    throw new Error('Could not connect to Slack');

  }

});


module.exports = (controller) => {
  controller.hears(
    /say announcement "(.+?)"/is,
    'direct_mention',
    (bot, message) => {
      console.log(message)
      message.match.shift() // skip full match
      const text = message.match.shift()
      const reply = {
        text,
        attachments: [
          {
            text: 'Which channel should I send to?',
            fallback: 'Which channel should I send to?',
            callback_id: 'announcement_interactive_channel',
            actions: [
              {
                name: 'channels_list',
                text: 'Which',
                type: 'select',
                data_source: 'channels',
              },
            ],
          },
        ],
      }
      bot.reply(message, reply)
    }
  )
  controller.on(
    'interactive_message_callback',
    async (bot, message) => {
      if (message.callback_id === 'announcement_interactive_channel') {
        console.dir(message, { depth: null })

        const reply = {
          text: message.original_message.text,
          attachments: [
            {
              text: 'Who should I send as?',
              fallback: 'Who should I send as?',
              callback_id: 'announcement_interactive_whom',
              actions: [
                {
                  name: 'send_as_list',
                  text: 'Whom?',
                  type: 'select',
                  options: [
                    {
                      text: 'The Clinic',
                      value: `${message.text},The Clinic`,
                    },
                    {
                      text: '3Shape',
                      value: `${message.text},3Shape`,
                    },
                  ],
                },
              ],
            },
          ],
        }
        bot.replyInteractive(message, reply)
      } else if (message.callback_id === 'announcement_interactive_whom') {
        console.dir(message, { depth: null })
        const [channel, username] = message.text.split(',')
        const emoji = {
          'The Clinic': ':theclinic_logo:',
          '3Shape': ':3shape:',
        }
        const say = {
          text: message.original_message.text,
          icon_emoji: emoji[username],
          username,
          channel,
        }
        bot.say(say, (err) => {
          if (err) {
            bot.replyInteractive(
              message,
              `Failed sent message to <#${channel}>`
            )
          } else {
            bot.replyInteractive(
              message,
              `Successfully sent message to <#${channel}>`
            )
          }
        })
      }
    }
  )
}
```

**Comment by casz** [comment]
The reason for `module.exports` is because it is in a separate file.

Consider updating your node js version to a newer LTS version.

Anyways you can fix the regex by using `const myRegex = new RegExp('say announcement "(.+?)"', 'is')`

**Comment by WisseHesNL** [comment]
Okay, I updated Node.JS to v10.15.3, it runs but when i say `/say announcement test` slack says 
![image](https://user-images.githubusercontent.com/31771656/56291817-45403c80-6126-11e9-8d02-9ce7750f038b.png)
And know my config is 
```node
module.exports = (controller) => {
  controller.hears(
    ('say announcement "(.+?)"', 'is'),
    'direct_mention',
    (bot, message) => {
      console.log(message)
      message.match.shift() // skip full match
      const text = message.match.shift()
      const reply = {
        text,
        attachments: [
          {
            text: 'Which channel should I send to?',
            fallback: 'Which channel should I send to?',
            callback_id: 'announcement_interactive_channel',
            actions: [
              {
                name: 'channels_list',
                text: 'Which',
                type: 'select',
                data_source: 'channels',
              },
            ],
          },
        ],
      }
      bot.reply(message, reply)
    }
  )
  controller.on(
    'interactive_message_callback',
    async (bot, message) => {
      if (message.callback_id === 'announcement_interactive_channel') {
        console.dir(message, { depth: null })

        const reply = {
          text: message.original_message.text,
          attachments: [
            {
              text: 'Who should I send as?',
              fallback: 'Who should I send as?',
              callback_id: 'announcement_interactive_whom',
              actions: [
                {
                  name: 'send_as_list',
                  text: 'Whom?',
                  type: 'select',
                  options: [
                    {
                      text: 'The Clinic',
                      value: `${message.text},The Clinic`,
                    },
                    {
                      text: '3Shape',
                      value: `${message.text},3Shape`,
                    },
                  ],
                },
              ],
            },
          ],
        }
        bot.replyInteractive(message, reply)
      } else if (message.callback_id === 'announcement_interactive_whom') {
        console.dir(message, { depth: null })
        const [channel, username] = message.text.split(',')
        const emoji = {
          'The Clinic': ':theclinic_logo:',
          '3Shape': ':3shape:',
        }
        const say = {
          text: message.original_message.text,
          icon_emoji: emoji[username],
          username,
          channel,
        }
        bot.say(say, (err) => {
          if (err) {
            bot.replyInteractive(
              message,
              `Failed sent message to <#${channel}>`
            )
          } else {
            bot.replyInteractive(
              message,
              `Successfully sent message to <#${channel}>`
            )
          }
        })
      }
    }
  )
}

```
but when i say `say announcement test` or `is test` doesn't even answer...

**Comment by casz** [comment]
I suggest you read the docs and fiddle some more with it.

it is a direct mention, not a slash command.

meaning you would have to type in some channel where the bot is located: `@mybot say announcement "your announcement"` the interactivity comes in via text replies.

**Comment by benbrown** [comment]
If you want to use a Slash command as shown, you can do:

```
controller.on('slash_command, function(bot, message) {

// if your slash command is /say announcement test
// this is "/say"
let command = message.command;

// this will be "announce test"
let text = message.text;

// do something

});

**Comment by benbrown** [comment]
Thanks for chiming in with the code sample @casz!

**Comment by WisseHesNL** [comment]
@casz I switched to a Slack App and now I need to configure Interactive Components, but it needs an URL to call when I select a channel from the dropdown
