### ISSUE TITLE
[SLACK] new SlackBotWorker() Error

### ISSUE THREAD

**Issue by roger-king** [howdyai/botkit#1639]
** DO NOT ERASE THESE INSTRUCTIONS WITHOUT READING THEM FIRST **

Please read this entire template before posting any issue to get faster response.

Open an issue on this repository with your topic or question, providing as much detail as possible. The more we know, the better we can help.

Before posting, search the repository to see if there's already an issue opened to avoid duplicates.

### Are you sure this is an issue with the Botkit core module?

Yes - botbuilder-adapter-slack

For all other questions, requests or help, please feel free to join the discussion slack : https://community.botkit.ai

### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as necessary to reproduce the issue or implement a missing functionality.

````
// Wrap code in markdown source tags
        // controller is the Botkit instance
        const slackbot = new SlackBotWorker(controller, message.incoming_message.conversation['team']);
        const user = userId;
        await bot.startPrivateConversation(user.id);
        await bot.say('Howdy, Mike');
````

### What was the result you received?

(node:45547) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'im' of undefined
    at SlackBotWorker.<anonymous> (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-adapter-slack/1.0.1/node_modules/botbuilder-adapter-slack/src/botworker.ts:87:45)
    at Generator.next (<anonymous>)
    at /Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-adapter-slack/1.0.1/node_modules/botbuilder-adapter-slack/lib/botworker.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-adapter-slack/1.0.1/node_modules/botbuilder-adapter-slack/lib/botworker.js:6:12)
    at SlackBotWorker.startPrivateConversation (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-adapter-slack/1.0.1/node_modules/botbuilder-adapter-slack/lib/botworker.js:86:16)
    at Object.<anonymous> (/Users/roger.king/development/joebot/src/events/onboarding.ts:13:18)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/roger.king/development/joebot/src/events/onboarding.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:45547) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:45547) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:45547) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sendActivity' of undefined
    at SlackBotWorker.<anonymous> (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/src/botworker.ts:107:56)
    at Generator.next (<anonymous>)
    at /Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/lib/botworker.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/lib/botworker.js:3:12)
    at _controller.middleware.send.run (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/src/botworker.ts:103:95)
    at next (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/ware/1.3.0/node_modules/ware/lib/index.js:82:27)
    at Ware.run (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/ware/1.3.0/node_modules/ware/lib/index.js:88:3)
    at Promise (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/src/botworker.ts:103:46)
    at new Promise (<anonymous>)
    at SlackBotWorker.<anonymous> (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/src/botworker.ts:100:16)
    at Generator.next (<anonymous>)
    at /Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/lib/botworker.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/lib/botworker.js:3:12)
    at SlackBotWorker.say (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/lib/botworker.js:93:16)

### What did you expect?

Bot starting private conversation with a different user and sending a message.

### Context:

- Botkit version: 4.0.1
- Messaging Platform: Slack
- Node version: 
- Os:
- Any other relevant information:

**Comment by benbrown** [comment]
You definitely do not want to create workers directly like that.  Only use `controller.spawn()` to do this.

**Comment by roger-king** [comment]
@benbrown Thanks for that. I could have sworn I tried with `controller.spawn()`. I got it working! I think I may have been forgetting the `await`
