### ISSUE TITLE
[SLACK] Error when creating onboarding experience

### ISSUE THREAD

**Issue by roger-king** [howdyai/botkit#1641]
** DO NOT ERASE THESE INSTRUCTIONS WITHOUT READING THEM FIRST **

Please read this entire template before posting any issue to get faster response.

Open an issue on this repository with your topic or question, providing as much detail as possible. The more we know, the better we can help.

Before posting, search the repository to see if there's already an issue opened to avoid duplicates.

### Are you sure this is an issue with the Botkit core module?

For all other questions, requests or help, please feel free to join the discussion slack : https://community.botkit.ai

### What are you trying to achieve or the steps to reproduce?

When building an onboarding experience I am receiving an error using bot `onboard` and `team_join`.

````
    controller.on('team_join', async (bot: SlackBotWorker, message: BotkitMessage) => {
        console.log('BOT USER', bot);
        console.log('message', message);
    });
````

### What was the result you received?

(node:52533) UnhandledPromiseRejectionWarning: Error: missing activity.conversation
    at BotkitConversationState.getStorageKey (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/src/conversationState.ts:22:19)
    at BotkitConversationState.ConversationState [as storageKey] (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-core/4.4.0/node_modules/botbuilder-core/src/conversationState.ts:38:38)
    at BotkitConversationState.load (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-core/4.4.0/node_modules/botbuilder-core/src/botState.ts:86:41)
    at BotStatePropertyAccessor.get (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-core/4.4.0/node_modules/botbuilder-core/src/botStatePropertyAccessor.ts:97:43)
    at DialogSet.createContext (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-dialogs/4.4.0/node_modules/botbuilder-dialogs/src/dialogSet.ts:114:59)
    at Botkit.<anonymous> (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/src/core.ts:685:52)
    at Generator.next (<anonymous>)
    at /Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/lib/core.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/lib/core.js:3:12)
    at Botkit.handleTurn (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botkit/4.0.1/node_modules/botkit/lib/core.js:438:16)
    at middleware.run (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-core/4.4.0/node_modules/botbuilder-core/src/botAdapter.ts:105:24)
    at runNext (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-core/4.4.0/node_modules/botbuilder-core/src/middlewareSet.ts:125:44)
    at Promise.resolve.handlers.(anonymous function) (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-core/4.4.0/node_modules/botbuilder-core/src/middlewareSet.ts:123:71)
    at SlackMessageTypeMiddleware.<anonymous> (/Users/roger.king/development/joebot/node_modules/.registry.npmjs.org/botbuilder-adapter-slack/1.0.1/node_modules/botbuilder-adapter-slack/src/messagetype_middleware.ts:77:15)

### What did you expect?

My server to log out the bot and message and eventually bot sends a message to the user.

### Context:

- Botkit version: 4.0.1
- Messaging Platform: Slack
- Node version: 
- Os:
- Any other relevant information:

**Comment by benbrown** [comment]
Thanks for the report, @roger-king.  Something must be different about that event type.  Normally, Botkit only is configured with `bot events`, not the other type of slack events.

**Comment by roger-king** [comment]
> Thanks for the report, @roger-king. Something must be different about that event type. Normally, Botkit only is configured with `bot events`, not the other type of slack events.

Is there a place I can see the bot events? Im happy to take a stab at tracking it down.

**Comment by benbrown** [comment]
It would seem the problem is that somehow that event is being created without the conversation field in the Activity. That would theoretically be caused by some issue inside this function:

https://github.com/howdyai/botkit/blob/master/packages/botbuilder-adapter-slack/src/slack_adapter.ts#L472

**Comment by benbrown** [comment]
AH, I know why this is happening.

The `team_join` event does not have a channel id, so the activity is ending up with conversation.id set to null.  There are probably other events like that too.  That is a bit problematic!

**Comment by benbrown** [comment]
Yes, there are definitely a lot of events that happen outside of channels.

I will need to do some experimentation to figure out the best solution for this.

**Comment by roger-king** [comment]
@benbrown 

Sounds nasty. Let me know if there is anything you want me to do :)

**Comment by benbrown** [comment]
This should be addressed soon!

**Comment by jebarjonet** [comment]
Awesome, I had today the exact same error for the event `app_uninstalled` when someone is uninstalling the app from its Slack team apps list.

**Comment by roger-king** [comment]
When testing out the onboarding and updating to 4.0.2; I got this type definition "bug" I created a new issue here: https://github.com/howdyai/botkit/issues/1670
