### ISSUE TITLE
Incorrect CMS token - throw meaningful error?

### ISSUE THREAD

**Issue by adrien-jacquot** [howdyai/botkit#1680]
### Are you sure this is an issue with the Botkit core module?

Yes!

### What are you trying to achieve or the steps to reproduce?

Simply trying to run botkit and have it talk to the CMS.
I launched the CMS with a `npm start` and created some dialogs there.
Then I launched botkit with `npm start` as well, and got an error. (see below)
In the end I realized the CMS token in the botkit .env file was not the same as the token in the cms .env file.

### What was the result you received?

node bot.js

** Your bot is using memory storage and will forget everything when it reboots!
** To preserve dialog state, specify a storage adapter in your Botkit config:
** const controller = new Botkit({storage: myStorageAdapter});
Enabling plugin:  Web Adapter
Enabling plugin:  Botkit CMS
Webhook endpoint online:  http://localhost:3000/api/messages
(node:27660) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Sandbox\PTA\pta-chatbot\botkit\node_modules\botkit-plugin-cms\lib\cms.js:91:41)
    at Request.self.callback (C:\Sandbox\PTA\pta-chatbot\botkit\node_modules\request\request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (C:\Sandbox\PTA\pta-chatbot\botkit\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (C:\Sandbox\PTA\pta-chatbot\botkit\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
(node:27660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### What did you expect?

A nice error message telling me my token was not the right one, or that I was not authorized,...

### Context:

- Botkit version: 4.0
- Messaging Platform: Web
- Node version: 9.4.0
- Os: Windows 10

**Comment by snakelecaps** [comment]
Maybe it because you are using Windows OS. anyone faced the same issue like Jaquinho?

**Comment by jpfcabral** [comment]
Same issue using Windows OS
