### ISSUE TITLE
Crash on DM message with only attachment

### ISSUE THREAD

**Issue by SomeoneWeird** [howdyai/botkit#172]
Code tries to use `message.text` when only `message.attachments` exists

```
/Users/adam/code/project/node_modules/botkit/lib/CoreBot.js:421
                                        message.text[Math.floor(Math.random() * message.text.length)]
                                                                                            ^

TypeError: Cannot read property 'length' of undefined
    at Conversation.tick (/Users/adam/code/project/node_modules/botkit/lib/CoreBot.js:421:93)
    at Task.tick (/Users/adam/code/project/node_modules/botkit/lib/CoreBot.js:609:36)
    at Object.Botkit.botkit.tick (/Users/adam/code/project/node_modules/botkit/lib/CoreBot.js:840:29)
    at Timeout._repeat (/Users/adam/code/project/node_modules/botkit/lib/CoreBot.js:790:24)
    at Timeout.wrapper [as _onTimeout] (timers.js:408:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

Works:
```js
bot.reply(message, {
  attachments: [ {
    title: "blah",
    text: "foo"
  } ]
})
```

Doesn't work:

```js
bot.startPrivateConversation(message, function (err, dm) {
  dm.say({
    attachments: [ {
      title: "blah",
      text: "foo"
    } ]
  })
})
```

The above works if i also pass `text: 'foo'` in the parent `dm.say` object.

**Comment by benbrown** [comment]
This has been fixed. Thank you!
