### ISSUE TITLE
Default botkit instance get an error about StorageKey

### ISSUE THREAD

**Issue by ugrozkr** [howdyai/botkit#1776]
İ'm new about botkit. When i setup and start default bot on web application, system returns us one of web app url and one another webhook url. I copied webhook url and add new microsoft bot framework emulator bot on interface, but system did not connect webhook bot it get same error each time you can see following error;

Experienced an error inside the turn handler Error: missing activity.conversation
    at BotkitConversationState.getStorageKey (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botkit\lib\conversationState.js:23:19)
    at BotkitConversationState.ConversationState [as storageKey] (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botbuilder-core\lib\conversationState.js:28:30)
    at BotkitConversationState.load (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botbuilder-core\lib\botState.js:62:41)
    at BotStatePropertyAccessor.get (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botbuilder-core\lib\botStatePropertyAccessor.js:32:38)
    at DialogSet.createContext (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botbuilder-dialogs\lib\dialogSet.js:102:46)
    at Botkit.<anonymous> (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botkit\lib\core.js:455:56)
    at Generator.next (<anonymous>)
    at C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botkit\lib\core.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botkit\lib\core.js:3:12)
(node:16596) UnhandledPromiseRejectionWarning: Error: missing activity.conversation
    at BotkitConversationState.getStorageKey (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botkit\lib\conversationState.js:23:19)
    at BotkitConversationState.ConversationState [as storageKey] (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botbuilder-core\lib\conversationState.js:28:30)
    at BotkitConversationState.load (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botbuilder-core\lib\botState.js:62:41)
    at BotStatePropertyAccessor.get (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botbuilder-core\lib\botStatePropertyAccessor.js:32:38)
    at DialogSet.createContext (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botbuilder-dialogs\lib\dialogSet.js:102:46)
    at Botkit.<anonymous> (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botkit\lib\core.js:455:56)
    at Generator.next (<anonymous>)
    at C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botkit\lib\core.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ugroz\Desktop\botkit\mybot\node_modules\botkit\lib\core.js:3:12)
(node:16596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by benbrown** [comment]
The emulator only works with the built-in Bot Framework adapter.
If you use the web adapter, you can connect directly to the bot's chat interface.
