### ISSUE TITLE
can't send message after mongodb query

### ISSUE THREAD

**Issue by juanpablo64** [howdyai/botkit#1832]
Hi, I seem to have a problem integrating mongoose for mongodb queries and botkit, in particular, I want to make the bot reply after getting some interview files stored in a database. this is more or less the process 

```
//inside controller.hears
.
.
.
// get the reference field and store it.
const saved_reference = message.reference;
LoadInterviewsAndAsk(bot,message,saved_reference)
.
.
.

function LoadInterviewsAndAsk(bot,message,saved_reference) {

    db.Interview
    .find({})
    .exec(function(err,interviews) {
        if (err){
            console.log(err);
            sendBotMessage(bot,message,"Hubo un error al cargar las entrevistas. Por favor, actualice para intentar de nuevo.",saved_reference)
        }
        else{
            sendBotMessage(bot,message,"se encontraron entrevistas",saved_reference)
        }
    })    
}

async function sendBotMessage(bot,message,envelope,saved_reference) {
    bot.changeContext(saved_reference);
    await bot.reply(message,envelope)
}
```

This is the error that I receive:

```
(node:9536) UnhandledPromiseRejectionWarning: TypeError: Cannot perform 'get' on
 a proxy that has been revoked
    at BotWorker.<anonymous> (C:\xampp\htdocs\webchatbot\node_modules\botkit\lib
\botworker.js:100:60)
    at Generator.next (<anonymous>)
    at C:\xampp\htdocs\webchatbot\node_modules\botkit\lib\botworker.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\xampp\htdocs\webchatbot\node_modules\botkit\lib\botworker.j
s:3:12)
    at _controller.middleware.send.run (C:\xampp\htdocs\webchatbot\node_modules\
botkit\lib\botworker.js:96:94)
    at next (C:\xampp\htdocs\webchatbot\node_modules\ware\lib\index.js:82:27)
    at Ware.run (C:\xampp\htdocs\webchatbot\node_modules\ware\lib\index.js:88:3)

    at Promise (C:\xampp\htdocs\webchatbot\node_modules\botkit\lib\botworker.js:
96:50)
    at new Promise (<anonymous>)
    at BotWorker.<anonymous> (C:\xampp\htdocs\webchatbot\node_modules\botkit\lib
\botworker.js:94:20)
    at Generator.next (<anonymous>)
    at C:\xampp\htdocs\webchatbot\node_modules\botkit\lib\botworker.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\xampp\htdocs\webchatbot\node_modules\botkit\lib\botworker.j
s:3:12)
    at BotWorker.say (C:\xampp\htdocs\webchatbot\node_modules\botkit\lib\botwork
er.js:93:16)
(node:9536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
```

**Comment by benbrown** [comment]
Call `await bot.changeContext(...)`
