### ISSUE TITLE
[OS X] Yo Error: EACCES: permission denied 

### ISSUE THREAD

**Issue by valdu02100** [howdyai/botkit#1907]
I managed to install yeoman on OS X Catalina.

However, when I run the 
`yo botkit`
I have the following error
```
Error: EACCES: permission denied, open '/Users/valentin/Library/Preferences/insight-nodejs/insight-yo.json.4064983394'
    at Object.openSync (fs.js:440:3)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/yo/node_modules/write-file-atomic/index.js:212:13)
    at Conf.set store [as store] (/usr/local/lib/node_modules/yo/node_modules/conf/index.js:142:19)
    at new Conf (/usr/local/lib/node_modules/yo/node_modules/conf/index.js:44:14)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:40:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:54:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/Users/valentin/Library/Preferences/insight-nodejs/insight-yo.json.4064983394'
}
```
I tried with sudo but the result is the same. I don't see this problem corrected. Any ideas?

**Comment by benbrown** [comment]
I think you are reporting this to the wrong repo. `botman` is something else completely unrelated to Botkit.

**Comment by valdu02100** [comment]
Youps, was an error in writing post ! I fix it !

**Comment by benbrown** [comment]
Gotcha.

Well, it's really hard to say what might be causing this, as this is a local filesystem permission issue.  Are you using the latest version of the generator? 

Perhaps try reinstalling yeoman?

**Comment by valdu02100** [comment]
I managed to recover the original project on 
https://botkit-facebook.glitch.me
But I wish yo would work.
Indeed it's related to OS X but I don't think I'm the only one who had this problem.

**Comment by benbrown** [comment]
Did you try reinstalling yeoman? The error you posted is from an internal package used by Yeoman, not Botkit.

I am not able to reproduce this error.
