### ISSUE TITLE
Slack API, modal, unable to find dialog error

### ISSUE THREAD

**Issue by nisheshshukla** [howdyai/botkit#1930]
I'm trying to set up a Slack API bot that creates a private conversation with a specific user by hearing `modal` in the main channel. Then it proceeds to ask a series of questions in a modal view using Slack API and botkit. The initial private message is just a message with two buttons, click on any of the buttons does nothing.  it never seems to understand that it is a `interactive_message` hence it never goes into  `controller.on('interactive_message', async(bot, message) `. It however works if I do not start a private conversation with the user and just initiate it in the channel.

Here is the code: 
````
        controller.hears('modal','message', async(bot, message) => {

            const responseCard = {
                attachments: [
                    {
                        text: '*blah blah*',
                        actions: [
                            {
                                name: 'option1',
                                type: 'button',
                                text: 'Option 1',
                                value: 'option1',
                            },
                            {
                                name: 'skip',
                                type: 'button',
                                text: 'Skip',
                                value: 'skip'
                            }
                        ],
                        callback_id: '1234',
                    }
                ]
            };

            await bot.startPrivateConversation(message.user);
            await bot.reply(message, responseCard);

        });
````
````
controller.on('interactive_message', async(bot, message) => {
            switch (message.actions[0].name) {
                case 'skip':
                    const trigger_id_modal = message.trigger_id;
                    const response_modal = await bot.api.views.open({
                        trigger_id: trigger_id_modal,
                        view: {
                            "type": "modal",
                            "callback_id": "skip-modal-identifier",
....
````

This is also the error that I'm getting: 
````
(node:40937) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:40937) UnhandledPromiseRejectionWarning: Error: DialogContext.continueDialog(): Can't continue dialog. A dialog with an id of 'standupDialog_default_prompt' wasn't found.
    at DialogContext.<anonymous> (/Users/nn/Development/chatBot/node_modules/botbuilder-dialogs/lib/dialogContext.js:248:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nn/Development/chatBot/node_modules/botbuilder-dialogs/lib/dialogContext.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:40937) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)

````
Any ideas anyone?

**Comment by sfny** [comment]
Hey @nisheshshukla. Have you been able to make progress on this issue? I'm confused as to why it would work in the public channel, but not privately. My first thought was to make sure your bot has the appropriate permissions.

**Comment by benbrown** [comment]
The error you are seeing would result from calls to bot.beginDialog, which are not included in the code you posted.

Also, if you call bot.startConversationWithUser and want to send messages into that 1:1 conversation, you should use bot.say instead of bot.reply.

bot.reply will always reply in the same channel as the `message` originated from.
