### ISSUE TITLE
Error when running with yarn pnp Error: A package is trying to access another package without the second one being listed as a dependency of the first one

### ISSUE THREAD

**Issue by megamit** [howdyai/botkit#1939]
### What are you trying to achieve or the steps to reproduce?

Attempting to run botkit project using yarn pnp

### What was the result you received?

```
yarn run start
~\Projects\bot\.pnp.js:28231
    throw firstError;
    ^

Error: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: request (via "request")
Required by: botkit-plugin-cms@npm:1.0.3 (via ~/bot/.yarn/cache/botkit-plugin-cms-npm-1.0.3-7c0d947730-2.zip/node_modules/botkit-plugin-cms/lib/)

```

### What did you expect?

It should work identically to installing dependencies without pnp

### Context:

- Botkit version:
^4.6.0
botkit-plugin-cms: 1.0.3
- Messaging Platform: Webex Teams
- Node version:  v13.7.0
- Os: Windows 10 x64 1902
- Any other relevant information:
Yarn version 2.0.0-rc.29

**Comment by benbrown** [comment]
Thanks for the report.  Can you give me steps to reproduce this?

**Comment by megamit** [comment]
It can be replicated using the yo generator
With this there is the same error but with a different dependency
```
npm i -g yo generator-botkit yarn
❯ yo botkit
❯ # click through the generator questions. Doesn't matter what platform (for this i chose webex)
❯ # enable yarn berry
❯ yarn set version berry
❯ # Reinstall dependencies with yarn
❯ yarn install
❯ # Attempt to run bot
❯ yarn start
/tmp/botkittest/.pnp.js:12893
    throw firstError;
    ^

Error: botkit tried to access botbuilder-core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: botbuilder-core (via "botbuilder-core")
Required by: botkit@npm:4.8.1 (via /tmp/botkittest/.yarn/cache/botkit-npm-4.8.1-b742e33da1-2.zip/node_modules/botkit/lib/)

Require stack:
- /tmp/botkittest/.yarn/cache/botkit-npm-4.8.1-b742e33da1-2.zip/node_modules/botkit/lib/testClient.js
- /tmp/botkittest/.yarn/cache/botkit-npm-4.8.1-b742e33da1-2.zip/node_modules/botkit/lib/index.js
- /tmp/botkittest/bot.js
    at Object.makeError (/tmp/botkittest/.pnp.js:6158:34)
    at resolveToUnqualified (/tmp/botkittest/.pnp.js:13518:37)
    at resolveRequest (/tmp/botkittest/.pnp.js:13608:27)
    at Object.resolveRequest (/tmp/botkittest/.pnp.js:13676:26)
    at Function.module_1.Module._resolveFilename (/tmp/botkittest/.pnp.js:12871:34)
    at Function.module_1.Module._load (/tmp/botkittest/.pnp.js:12756:40)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/botkittest/.yarn/cache/botkit-npm-4.8.1-b742e33da1-2.zip/node_modules/botkit/lib/testClient.js:19:27)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
```

**Comment by benbrown** [comment]
I am not a yarn expert - you are doing this instead of using npm?

**Comment by megamit** [comment]
Yes im using it wherever possible. It allows me to have less node_modules folders sprinkled across my storage.

I think this is because although botbuilder is a dependency of botkit (which itself imports botbuilder-core), botkit doesnt have botbuilder-core in its package.json.
yarn pnp doesnt allow packages to import other node modules that arent in package.json

**Comment by benbrown** [comment]
Ah! Ok. I'll take a look.
