### ISSUE TITLE
Experienced an error inside the turn handler TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string

### ISSUE THREAD

**Issue by ilyago** [howdyai/botkit#1974]
getting an error on basic setup when receiving webhook

- Botkit version: 4.9.0
- botbuilder-adapter-facebook: 1.0.10
- Express: 4.17.1
- Messaging Platform: Facebook
- Node version: 10.15.3
- Os: Windows 10

```
Experienced an error inside the turn handler TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hmac.update (internal/crypto/hash.js:58:11)
    at FacebookAdapter.<anonymous> (D:\WORK\aaaaaaaa\functions\node_modules\botbuilder-adapter-facebook\lib\facebook_adapter.js:418:18)
    at Generator.next (<anonymous>)
    at D:\WORK\aaaaaaaa\functions\node_modules\botbuilder-adapter-facebook\lib\facebook_adapter.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (D:\WORK\aaaaaaaa\functions\node_modules\botbuilder-adapter-facebook\lib\facebook_adapter.js:11:12)
    at FacebookAdapter.verifySignature (D:\WORK\aaaaaaaa\functions\node_modules\botbuilder-adapter-facebook\lib\facebook_adapter.js:415:16)
    at FacebookAdapter.<anonymous> (D:\WORK\aaaaaaaa\functions\node_modules\botbuilder-adapter-facebook\lib\facebook_adapter.js:328:29)
    at Generator.next (<anonymous>)
    at D:\WORK\aaaaaaaa\functions\node_modules\botbuilder-adapter-facebook\lib\facebook_adapter.js:15:71
(node:6060) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined

```

**Comment by benbrown** [comment]
This seems like an issue with the verifySignature method. Are you sure you are properly specifying the required verify token, app secret, etc?

**Comment by ilyago** [comment]
I have removed and added webhook again on Facebook to make sure it was not different
here is the full code that generates an error when a message is received

```
const
express = require('express'),
bodyParser = require('body-parser'),
webserver = express().use(bodyParser.json()).use(bodyParser.urlencoded({ extended: true }))

const { Botkit } = require('botkit')
const { FacebookAdapter, FacebookEventTypeMiddleware } = require('botbuilder-adapter-facebook')

const adapter = new FacebookAdapter({
	verify_token: 'aaaaaaaaaa',
	app_secret: 'aaaaaaaaaa',
	getAccessTokenForPage: async(pageId) => { 
    const token = 'aaaaaaaaaa'
    return token;
  }
})

adapter.use(new FacebookEventTypeMiddleware())

const controller = new Botkit({
    webhook_uri: '/api/messages',
    adapter,
    webserver
})

controller.ready(async () => {
    controller.hears('message,direct_message', async(bot, message) => {
        await bot.reply(message, 'I heard it');
    })
})

webserver.listen(8080)
```

**Comment by ericzon** [comment]
@ilyago @benbrown I found the problem and a possible workaround :) 
It fails because in that point you have already parsed the body. Ensure that rawBody has value in that step.

**Comment by rem4ik4ever** [comment]
I'm having similar issue. 
However I'm trying to integrate with keystonejs, which allows to extend express app. 

This looks like an express issue. Can anyone suggest any solution?
