### ISSUE TITLE
pass option { useUnifiedTopology: true } to mongo

### ISSUE THREAD

**Issue by dcsan** [howdyai/botkit#2005]
at startup i always see this warning, due to how you're initialize the mongo driver:

> (node:39924) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

> node --trace-deprecation dist/index.js

```
(node:40208) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
    at /Users/dc/dev/exiteer/xbot/cofbot/node_modules/mongodb/lib/operations/connect.js:333:5
    at parseConnectionString (/Users/dc/dev/exiteer/xbot/cofbot/node_modules/mongodb/lib/core/uri_parser.js:685:3)
    at connect (/Users/dc/dev/exiteer/xbot/cofbot/node_modules/mongodb/lib/operations/connect.js:277:3)
    at /Users/dc/dev/exiteer/xbot/cofbot/node_modules/mongodb/lib/mongo_client.js:222:5
    at maybePromise (/Users/dc/dev/exiteer/xbot/cofbot/node_modules/mongodb/lib/utils.js:719:3)
    at MongoClient.connect (/Users/dc/dev/exiteer/xbot/cofbot/node_modules/mongodb/lib/mongo_client.js:218:10)
    at Function.MongoClient.connect (/Users/dc/dev/exiteer/xbot/cofbot/node_modules/mongodb/lib/mongo_client.js:440:22)
    at MongoDbStorage.<anonymous> (/Users/dc/dev/exiteer/xbot/cofbot/node_modules/botbuilder-storage-mongodb/lib/MongoDbStorage.js:38:55)
    at Generator.next (<anonymous>)
    at /Users/dc/dev/exiteer/xbot/cofbot/node_modules/botbuilder-storage-mongodb/lib/MongoDbStorage.js:7:71
```

btw it's not enabled as an app level pass through

doesn't work:

```js
if (process.env.MONGO_URI) {
  storage = new MongoDbStorage({
    url: process.env.MONGO_URI,
    useUnifiedTopology: true
  })
```

**Comment by benbrown** [comment]
This looks like a problem with `botbuilder-storage-mongodb`, not with Botkit. You should open a ticket here:

https://github.com/botbuilder-contrib/botbuilder-storage-mongodb
