### ISSUE TITLE
[Facebook] Conversation crashes when big emoji or like is sent

### ISSUE THREAD

**Issue by crummy** [howdyai/botkit#219]
1. Start a conversation with a bot (i.e. in a `bot.startConversation()` section, when prompted by `convo.say()`)
2. Click "Like" to send a big thumbs up, or click the :) button and send a large facebook emoji thing

Behaviour: Bot loops TypeError and crashes

Here's my listener:

```
controller.hears("", 'message_received', function(bot, message) {
  bot.startConversation(message, function(err, convo) {
    convo.ask("send me a facebook emoji image to crash me. they are under the `:)` on the web interface. or just click the like button", function(response, convo) {
      convo.say("guess you didn't send me an emoji. instead I got: " + response.text);
      convo.next();
    });
  });
});
```

The crashlog:
```
GOT A MESSAGE HOOK
TypeError: Cannot read property 'trim' of undefined
    at Conversation.capture (C:\Users\Malcolm\Dropbox\code\janbot\node_modules\botkit\lib\CoreBot.js:64:42)
    at Conversation.handle (C:\Users\Malcolm\Dropbox\code\janbot\node_modules\botkit\lib\CoreBot.js:96:22)
    at C:\Users\Malcolm\Dropbox\code\janbot\node_modules\botkit\lib\CoreBot.js:871:31
    at Object.bot.findConversation (C:\Users\Malcolm\Dropbox\code\janbot\node_modules\botkit\lib\Facebook.js:97:25)
    at C:\Users\Malcolm\Dropbox\code\janbot\node_modules\botkit\lib\CoreBot.js:869:21
    at next (C:\Users\Malcolm\Dropbox\code\janbot\node_modules\ware\lib\index.js:82:27)
    at Ware.run (C:\Users\Malcolm\Dropbox\code\janbot\node_modules\ware\lib\index.js:88:3)
    at Object.Botkit.botkit.receiveMessage (C:\Users\Malcolm\Dropbox\code\janbot\node_modules\botkit\lib\CoreBot.js:864:35)
    at C:\Users\Malcolm\Dropbox\code\janbot\node_modules\botkit\lib\Facebook.js:136:45
    at Layer.handle [as handle_request] (C:\Users\Malcolm\Dropbox\code\janbot\node_modules\express\lib\router\layer.js:95:5)
```

Botkit `0.1.1`
Windows 10, ngrok
Node `v5.4.0`

**Comment by benbrown** [comment]
This code has been merged in! Thanks for helping to fix this.
