### ISSUE TITLE
setting up botkit with RTM, bot is undefined

### ISSUE THREAD

**Issue by DavidKarasek** [howdyai/botkit#230]
I am setting up a slack bot using the example code from the slack bot button example. Whenever I try to run the server I am getting this error, 

```
 debug: Setting up a handler for message_received
 info: ** Configuring app as a Slack App!
/app/node_modules/botkit/lib/SlackBot.js:24
             throw new Error('Missing oauth config details', bot);
                                                          ^

 ReferenceError: bot is not defined
    at Object.Slackbot.slack_botkit.configureSlackApp (/app/node_modules/botkit/lib/SlackBot.js:24:61)
    at Object.<anonymous> (/app/server.js:13:4)
     at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
     at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
     at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
     at node.js:405:3
```

I didn't include the code since I am using the example as exactly posted. I have setup an app for it on my team. As far as I can tell I have done everything correctly.

**Comment by DavidKarasek** [comment]
This was a token issue. Thought I double checked those before posting the issue.
