### ISSUE TITLE
Update examples to match with config change done in #214 

### ISSUE THREAD

**Issue by lauripiisang** [howdyai/botkit#245]
You've updated the configuration parameters, but you have examples using old code, ending up in errors:
```
root@998e9f2f3991:/botkit/examples# node slackbutton_bot.js 
info: ** Using simple storage. Saving data to ./db_slackbutton_bot/
info: ** Setting up custom handlers for processing Slack messages
info: ** Configuring app as a Slack App!
/botkit/lib/SlackBot.js:211
        slack_botkit.webserver.use(express.static(slack_botkit.config.webserver.static_dir || __dirname + '/public'));
                                                                               ^

TypeError: Cannot read property 'static_dir' of undefined
    at Object.Slackbot.slack_botkit.setupWebserver (/botkit/lib/SlackBot.js:211:80)
    at Object.<anonymous> (/botkit/examples/slackbutton_bot.js:46:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
```
Mind you, when deprecating config, you might also want to bump versions!
I'll deal with this myself if I have time later today.

**Comment by anonrig** [comment]
@benbrown let's bump the version asap.
