### ISSUE TITLE
Defining JSON File Storage for Facebook Bot Causes Error

### ISSUE THREAD

**Issue by djeraseit** [howdyai/botkit#262]
info: *\* Using simple storage. Saving data to botlog.json
/var/www/html/botkit/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: ENOTDIR: not a directory, mkdir '/var/www/html/botkit/botlog.json/teams'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Function.sync (/var/www/html/botkit/node_modules/mkdirp/index.js:71:13)
    at new Store (/var/www/html/botkit/node_modules/jfs/lib/Store.js:307:16)
    at module.exports (/var/www/html/botkit/lib/storage/simple_storage.js:35:20)
    at Botkit (/var/www/html/botkit/lib/CoreBot.js:978:26)
    at Object.Facebookbot (/var/www/html/botkit/lib/Facebook.js:9:27)
    at Object.<anonymous> (/var/www/html/botkit/facebook_bot.js:86:25)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by hobofan** [comment]
Looks like you already had a existing file called `botlog.json`.

For me it was also unituitive at first, but the `json_file_store` value should be a directory name and not the name of a json file where it should be saved.

**Comment by peterswimm** [comment]
@djeraseit did the above solve your problem?

**Comment by peterswimm** [comment]
Closed as answered.
