### ISSUE TITLE
Successful ping-pong but RTM not opened?

### ISSUE THREAD

**Issue by deubaka** [howdyai/botkit#388]
Hi! I'm experiencing this issue when the bot is running from some time without user interaction (usually overnight), when sending a message it will crash caused by `not opened`. 

However, upon checking the debug logs, it shows that Ping-Pong is working fine. There is already a `retry` set at 500 (already tried setting to `Infinity` too), but it seems it doesn't work too. Upon checking the logs, there is no event fired for 'rtm_close', so the reconnection didn't even get triggered.

I'm still checking on what causes it, but if anyone could point or suggest me on how to resolve this issue, it would be greatly appreciated.

Cheers,
Deu

```
debug: No handler for tick
debug: PONG received
debug: PONG received
debug: PONG received
debug: No handler for tick
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO undefined undefined
debug: DEFAULT SLACK MSG RECEIVED RESPONDER
debug: No handler for reconnect_url
debug: No handler for tick
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO U0NDPGE4D D1RKEBD9V
debug: DEFAULT SLACK MSG RECEIVED RESPONDER
debug: SAY { id: 1, type: 'typing', channel: 'D1RKEBD9V' }
Error: not opened
    at WebSocket.send (/opt/bots/gbot/node_modules/ws/lib/WebSocket.js:218:38)
    at Object.bot.send (/opt/bots/gbot/node_modules/botkit/lib/Slackbot_worker.js:345:25)
    at /opt/bots/gbot/node_modules/botkit/lib/CoreBot.js:808:24
    at next (/opt/bots/gbot/node_modules/ware/lib/index.js:82:27)
    at Ware.run (/opt/bots/gbot/node_modules/ware/lib/index.js:88:3)
    at Object.worker.say (/opt/bots/gbot/node_modules/botkit/lib/CoreBot.js:807:36)
    at SlackBot.dispatchMessage (/opt/bots/gbot/lib_botbuilder_compat/bots/SlackBot.js:255:18)
    at /opt/bots/gbot/lib_botbuilder_compat/bots/SlackBot.js:132:23
    at Object.bot.identifyTeam (/opt/bots/gbot/node_modules/botkit/lib/Slackbot_worker.js:250:20)
    at dispatch (/opt/bots/gbot/lib_botbuilder_compat/bots/SlackBot.js:130:17)
    at Object.<anonymous> (/opt/bots/gbot/lib_botbuilder_compat/bots/SlackBot.js:150:21)
    at Object.Botkit.botkit.trigger (/opt/bots/gbot/node_modules/botkit/lib/CoreBot.js:779:49)
    at Object.<anonymous> (/opt/bots/gbot/node_modules/botkit/lib/SlackBot.js:589:34)
    at Object.Botkit.botkit.trigger (/opt/bots/gbot/node_modules/botkit/lib/CoreBot.js:779:49)
    at /opt/bots/gbot/node_modules/botkit/lib/CoreBot.js:866:32
    at Object.bot.findConversation (/opt/bots/gbot/node_modules/botkit/lib/Slackbot_worker.js:594:9)
```

**Comment by thbar** [comment]
@deubaka do you still see that error, or did it went away?

**Comment by peterswimm** [comment]
Closed due to inactivity.

**Comment by deubaka** [comment]
Sorry wasn't able to reply. For some reason, it did go away after several days.s Still unsure what caused it though. Thanks
