### ISSUE TITLE
Crashes on bot.findConversation is not a function when trying to start conversation

### ISSUE THREAD

**Issue by danielckv** [howdyai/botkit#495]
Running the example of **Facebook's conversation**  from Botkit's docs and getting crashed from this code:

```
2016-11-14T09:26:15.803803+00:00 app[web.1]: TypeError: bot.findConversation is not a function
2016-11-14T09:26:15.803814+00:00 app[web.1]:     at /app/node_modules/botkit/lib/CoreBot.js:979:21
2016-11-14T09:26:15.803815+00:00 app[web.1]:     at next (/app/node_modules/ware/lib/index.js:82:27)
2016-11-14T09:26:15.803815+00:00 app[web.1]:     at Ware.run (/app/node_modules/ware/lib/index.js:88:3)
2016-11-14T09:26:15.803817+00:00 app[web.1]:     at Object.Botkit.botkit.receiveMessage (/app/node_modules/botkit/lib/CoreBot.js:974:35)
2016-11-14T09:26:15.803818+00:00 app[web.1]:     at /app/node_modules/botkit/lib/Facebook.js:224:45
2016-11-14T09:26:15.803818+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-11-14T09:26:15.803851+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2016-11-14T09:26:15.803852+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2016-11-14T09:26:15.803853+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-11-14T09:26:15.803854+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
2016-11-14T09:26:15.803855+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2016-11-14T09:26:15.803856+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2016-11-14T09:26:15.803856+00:00 app[web.1]:     at serveStatic (/app/node_modules/serve-static/index.js:75:16)
2016-11-14T09:26:15.803857+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-11-14T09:26:15.803858+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
2016-11-14T09:26:15.803858+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:280:7
```

**Comment by peterswimm** [comment]
Can anyone reproduce the crash? @danielckv can you tell us a little bit about your dev environment?

**Comment by danielckv** [comment]
I’m using Heroku as my hosting and the regular code for Facebook bot from your examples with my token and validation token page.

**Comment by peterswimm** [comment]
We think this is now fixed. We will try to publish .4.2 later today, but in the meantime you can pull the latest from master to confirm the fix.

**Comment by jonchurch** [comment]
@danielckv Are you running the example code from [here](https://github.com/howdyai/botkit/blob/master/readme-facebook.md#working-with-facebook-messenger) or the [facebook_bot.js](https://github.com/howdyai/botkit/blob/master/facebook_bot.js) example included in the repo?

Not currently able to replicate this on Heroku using either of those files unchanged. I broke the spawned bot being passed into setupWebserver and that gave me a similar error. I don't believe this would be connected to the Hostname set by botkit, which #493 addresses

**Comment by danielckv** [comment]
@jonchurch here is my setup code for the bot:

botController.setupWebserver(port, function(err, webserver) {

    botController.createWebhookEndpoints(botController.webserver, botkit, function() {
        console.log('ChatBot service is online.');
    });
});

botController.on('facebook_optin', function(bot, message) {
            bot.reply(message, 'Welcome to my app!');
        });

     botController.hears(['hello'], 'message_received', function(bot, message) {
            bot.reply(message, 'Hey there.');
        });

**Comment by jonchurch** [comment]
Is the `botkit` variable passed into `botController.createWebhookEndpoints` a spawned bot?

If not, try this
```
var bot = botController.spawn({})

botController.setupWebserver(port, function(err, webserver) {

    botController.createWebhookEndpoints(botController.webserver, bot, function() {
        console.log('ChatBot service is online.');
    });
});
```

**Comment by danielckv** [comment]
@jonchurch it appears that I didn't span the bot argument before running createWebhookendpoints.
I think it should be automatically as i don't see any special parameters that passed in Spawn function..

**Comment by benbrown** [comment]
I believe @jonchurch is correct here @danielckv... make sure you spawn a bot like he did in his example, and pass that bot into the createWebhookEndpoints function.

**Comment by peterswimm** [comment]
@danielckv Did the above fix your issue?

**Comment by danielckv** [comment]
@peterswimm yep.
