### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by patrickml** [howdyai/botkit#524]
I am trying to send a simple `hello` message to slack when a user mentions the bot, but forsome reason I am getting this error:
```sh
nfo: ** No persistent storage method specified! Data may be lost when process shuts down.
info: ** Setting up custom handlers for processing Slack messages
info: ** API CALL: https://slack.com/api/rtm.start
notice: ** BOT ID: demobot ...attempting to connect to RTM!
notice: RTM websocket opened
/Users/patricklewis/Documents/sites/npm/applications/utu-example-botkit/node_modules/botkit/lib/CoreBot.js:852
                        cb.apply(this, [bot, message]);
                          ^

TypeError: Cannot read property 'apply' of undefined
    at Object.<anonymous> (/Users/patricklewis/Documents/sites/npm/applications/utu-example-botkit/node_modules/botkit/lib/CoreBot.js:852:27)
    at Object.Botkit.botkit.trigger (/Users/patricklewis/Documents/sites/npm/applications/utu-example-botkit/node_modules/botkit/lib/CoreBot.js:879:49)
    at Object.<anonymous> (/Users/patricklewis/Documents/sites/npm/applications/utu-example-botkit/node_modules/botkit/lib/SlackBot.js:739:38)
    at Object.Botkit.botkit.trigger (/Users/patricklewis/Documents/sites/npm/applications/utu-example-botkit/node_modules/botkit/lib/CoreBot.js:879:49)
    at /Users/patricklewis/Documents/sites/npm/applications/utu-example-botkit/node_modules/botkit/lib/CoreBot.js:983:32
    at Object.bot.findConversation (/Users/patricklewis/Documents/sites/npm/applications/utu-example-botkit/node_modules/botkit/lib/Slackbot_worker.js:678:9)
    at /Users/patricklewis/Documents/sites/npm/applications/utu-example-botkit/node_modules/botkit/lib/CoreBot.js:979:21
    at next (/Users/patricklewis/Documents/sites/npm/applications/utu-example-botkit/node_modules/ware/lib/index.js:82:27)
    at Ware.run (/Users/patricklewis/Documents/sites/npm/applications/utu-example-botkit/node_modules/ware/lib/index.js:88:3)
    at Object.Botkit.botkit.receiveMessage (/Users/patricklewis/Documents/sites/npm/applications/utu-example-botkit/node_modules/botkit/lib/CoreBot.js:974:35)
```

this is my reply function

```js
export default (bot, message) => {
  const reply = 'Hey there.';
  bot.reply(message, reply);
};
```

**Comment by patrickml** [comment]
Never mind it was a mindless mistake

**Comment by thierryskoda** [comment]
@patrickml What was it ? I currently have the same exact error

**Comment by patrickml** [comment]
@thierryskoda I didn't pass the correct information into the `createWebhookEndpoints`

```js
controller.setupWebserver(3001, () => {
  controller.createWebhookEndpoints(controller.webserver, bot);
});
```

**Comment by peterswimm** [comment]
Thanks for sharing the solution!
