### ISSUE TITLE
certificate has expired 

### ISSUE THREAD

**Issue by thierryskoda** [howdyai/botkit#549]
Hey! I have this in my logs. 

Anyone know what it is?

```Error in Botkit Studio Stats: { Error: certificate has expired 
at Error (native) 
at TLSSocket.<anonymous> (_tls_wrap.js:1062:38) 
at emitNone (events.js:86:13) 
at TLSSocket.emit (events.js:185:7) 
at TLSSocket._finishInit (_tls_wrap.js:586:8) 
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'CERT_HAS_EXPIRED' } ```

**Comment by benbrown** [comment]
This was a temporary issue with our Botkit.ai server. Apologies!
