### ISSUE TITLE
Failing with --use-strict due to variables used without being locally scoped

### ISSUE THREAD

**Issue by alecl** [howdyai/botkit#589]
Looking at latest... Did some local vars become global on purpose or move somewhere else since 2.2?

1) Inside Slackbot.js

latest 4.9
ref: https://github.com/howdyai/botkit/blob/v0.4.9/lib/SlackBot.js#L172

                bot = slack_botkit.spawn(team);

before: 2.2
ref: https://github.com/howdyai/botkit/blob/v0.2.2/lib/SlackBot.js#L146

                var bot = slack_botkit.spawn(team);

2) Inside CoreBot.js -> botkit.hears_regexp

latest 4.9
ref: https://github.com/howdyai/botkit/blob/v0.4.9/lib/CoreBot.js#L902

                if (match = message.text.match(test)) {

before: 2.2
ref: https://github.com/howdyai/botkit/blob/v0.2.2/lib/CoreBot.js#L709

                var match = message.text.match(test);

Where is bot defined? Where is match defined? Are they global now?

I ask in particular because at some point between 2.2 (I just re-verified this is fine) and 4.9 being able to debug with VSCode broke and it seems like it's because **another thread is clobbering these variables that are now more widely scoped instead of local**. Yes, debug:false is set for controller.

So, either VSCode is doing something wrong or there's a real issue with scoping that makes me fear other multithreading issues are a risk now as well and this might just be an easy way to repeat but other bugs might be laying hidden.

With the base code from https://github.com/howdyai/botkit-studio-starter doing a simple "uptime" DM

In Events API mode it breaks at 1) above with this stack trace

```
                bot = slack_botkit.spawn(team);
                    ^
ReferenceError: bot is not defined
    at /Users/alec/gitproj/mbot/node_modules/botkit/lib/SlackBot.js:172:21
    at Command.callback (/Users/alec/gitproj/mbot/node_modules/botkit-storage-redis/src/index.js:41:17)
    at normal_reply (/Users/alec/gitproj/mbot/node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/Users/alec/gitproj/mbot/node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.Parser.returnReply (/Users/alec/gitproj/mbot/node_modules/redis/index.js:188:18)
    at JavascriptRedisParser.execute (/Users/alec/gitproj/mbot/node_modules/redis-parser/lib/parser.js:491:12)
    at Socket.<anonymous> (/Users/alec/gitproj/mbot/node_modules/redis/index.js:267:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
```

I switched back to RTM mode and there it breaks at 2) above with this stack trace

```
/Users/alec/gitproj/mbot/node_modules/botkit/lib/CoreBot.js:902
                if (match = message.text.match(test)) {
                          ^
ReferenceError: match is not defined
    at botkit.hears_regexp (/Users/alec/gitproj/mbot/node_modules/botkit/lib/CoreBot.js:902:27)
    at Object.<anonymous> (/Users/alec/gitproj/mbot/node_modules/botkit/lib/CoreBot.js:943:42)
    at Object.botkit.trigger (/Users/alec/gitproj/mbot/node_modules/botkit/lib/CoreBot.js:972:49)
    at Object.<anonymous> (/Users/alec/gitproj/mbot/node_modules/botkit/lib/SlackBot.js:686:34)
    at Object.botkit.trigger (/Users/alec/gitproj/mbot/node_modules/botkit/lib/CoreBot.js:972:49)
    at /Users/alec/gitproj/mbot/node_modules/botkit/lib/CoreBot.js:1076:32
    at Object.module.exports.bot.findConversation (/Users/alec/gitproj/mbot/node_modules/botkit/lib/Slackbot_worker.js:685:9)
    at /Users/alec/gitproj/mbot/node_modules/botkit/lib/CoreBot.js:1072:21
    at next (/Users/alec/gitproj/mbot/node_modules/ware/lib/index.js:82:27)
    at Ware.run (/Users/alec/gitproj/mbot/node_modules/ware/lib/index.js:88:3)
```

**Comment by jonchurch** [comment]
Hi @alecl! This is a great issue thank you!

When experiencing issue 1.: Are you using a slack app or is this a custom integration?

**Comment by alecl** [comment]
Hey, Jonathan!

Using a Slack App. Basically the sample setup here:
https://github.com/howdyai/botkit/blob/master/docs/slack-events-api.md

**Comment by alecl** [comment]
The error is shown in the debug console of the bot code. You just need to setup a launch.json to run the bot.js and hit F5 to start the interactive debug mode. I added dotenv to read clientId and clients ref from file but you can also just put in the values in the env section of VSCode's launch.json too.

**Comment by alecl** [comment]
Those other places in the code you mentioned it's locally scoped to another block not as a parent area.

So, I added var statements for those variables in those two areas I linked and that fixed the problem. HOWEVER, I figured out the reason it was complaining at all was because I was running node when debugging with

--use-strict

🤕 

So this is my user error. That being said, locally scoping variables is a good practice that cuts down on unexpected interactions and other bugs so probably worth doing. I run all my projects with use-strict out of habit.

**Comment by jonchurch** [comment]
Glad to see you found a resolution, you are right though that a lot of devs run with use strict without question. 

To resolve this issue, am I understanding you correctly that you suggest these variables be locally scoped to their parent functions?

**Comment by alecl** [comment]
Right.

For the first one:

     var bot = slack_botkit.spawn(team);

For the second one:

```
var match = message.text.match(test);
if (match) {
```
