### ISSUE TITLE
Cannot import botkit into ionic 2 app - any workarounds?

### ISSUE THREAD

**Issue by TheJimFactor** [howdyai/botkit#636]
Application is the starter ionic 2 project:  `ionic start MyIonic2Project tutorial --v2`

I have gotten modules like lodash and slack to work with this kind of import:
```
import * as slack from 'slack'; // this works https://www.npmjs.com/package/slack
import * as _ from 'lodash'; // this works
import * as Botkit  from 'botkit'; // this does not work 
```

Also got bcryptjs working with a more difficult workaround involving downloading its min.js including it in the www/index.html   `<script src="bcrypt.min.js"></script>`  and using a `declare var dcodeIO: any;`from https://x-team.com/blog/include-javascript-libraries-in-an-ionic-2-typescript-project/ however I do not know how I would do that method with botkit.

More complete error and trace when trying `import * as Botkit from 'botkit'`:
```
Runtime Error
Cannot find module "node-uuid"
```

```
Error: Cannot find module "node-uuid"
    at webpackMissingModule (http://localhost:8100/build/main.js:227795:74)
    at Object.<anonymous> (http://localhost:8100/build/main.js:227795:160)
    at Object.<anonymous> (http://localhost:8100/build/main.js:228215:4)
    at Object.<anonymous> (http://localhost:8100/build/main.js:228217:30)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:203015:13)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:147152:22)
    at Object.<anonymous> (http://localhost:8100/build/main.js:148379:30)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
```

**Comment by monte-hayward** [comment]
this issue also happens with a require:
`const Botkit = require('botkit');`
My temporary workaround was to add node-uuid as a dependency to my project.
Odd since it's declared in botkit's package.json

**Comment by peterswimm** [comment]
@monte-hayward did you ever figure this out?
