### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by MatejMecka** [howdyai/botkit#693]
Hello there. I had a bot that ran perfectly until one day it started randomly crashing with this:

```
/root/GoogleBot/node_modules/botkit/lib/CoreBot.js:896
        for (var t = 0; t < tests.length; t++) {
                                 ^

TypeError: Cannot read property 'length' of undefined
    at Botkit.botkit.hears_regexp (/root/GoogleBot/node_modules/botkit/lib/CoreBot.js:896:34)
    at Object.<anonymous> (/root/GoogleBot/node_modules/botkit/lib/CoreBot.js:957:42)
    at Object.Botkit.botkit.trigger (/root/GoogleBot/node_modules/botkit/lib/CoreBot.js:988:49)
    at Object.<anonymous> (/root/GoogleBot/node_modules/botkit/lib/SlackBot.js:724:34)
    at Object.Botkit.botkit.trigger (/root/GoogleBot/node_modules/botkit/lib/CoreBot.js:988:49)
    at /root/GoogleBot/node_modules/botkit/lib/CoreBot.js:1090:32
    at Object.bot.findConversation (/root/GoogleBot/node_modules/botkit/lib/Slackbot_worker.js:751:9)
    at /root/GoogleBot/node_modules/botkit/lib/CoreBot.js:1086:21
    at next (/root/GoogleBot/node_modules/ware/lib/index.js:82:27)
    at Ware.run (/root/GoogleBot/node_modules/ware/lib/index.js:88:3)
```

My bot now crashes on strings it doesn't recognize and on direct commands. But it doesn't crash on commands that have regex.

It'll crash on direct commands but not on regexes.

It won't crash on this block:
```
controller.hears('weather (.*)','direct_message,direct_mention,mention',function(bot,message) { 
	 var  fullmessage = message  
	 var city = message.match[1];
	 var api = "http://api.openweathermap.org/data/2.5/weather?q=" + city +  "&units=metric&appid=" + config.weathertoken
	 request(api, function(error, response, body) {
        if (!error && response.statusCode == 200) {
        // Try to parse the json. If it errors it gets caught.
        var weatherjson = JSON.parse(body);
        var weather = weatherjson['weather'][0]['main'];
        var temperaturejson =  weatherjson['main']['temp']
        var temperature = Math.round(temperaturejson)
        bot.reply(message, "The weather for " + city + " is: " + weather + " with a temperature of " + temperature + "°C");
            } 
        else {
              console.error(error);
              console.log(response);
            }
	 });
})
```

but it'll crash on this simple block:
```
controller.hears(triggers.love,'direct_message,direct_mention,mention',function(bot,message) { 
	bot.reply(message,"No.")
})
```

If you think it's triggers.js fault that it crashes it isn't.

```
controller.hears('exit','direct_message,direct_mention,mention',function(bot,message) { 
        if(message.user == config.admin){
	bot.reply(message, "Ok. Shutting down")
	console.log("Shutted down 'by admin...")	
	process.exit(1);
	}
	else{
	bot.reply(message, ":warning: I'm sorry I'm afraid I can't let you do that")
	console.log("User: " + message.user + " Tried to shut me down :c")
}
})
```

It crashes on a block like this. No Message no return. Nothing. Other users have successfully turned my bot and it simply returned that botkit crashed with the error above.

If you are curious for my triggers.js file it's this

```module.export = {

search: [ "get a girlfriend","get a boyfriend","get a date", "get a prom"],
info : ["help", "info", "commands", "instructions"],
love : ["do you like me", "do you love me", "will you be my valentines", "can i marry you", "will you marry me"]




}
```

----------

Version: Ubuntu 16.04
Node Version: v4.2.6 & v6.0.0
Botkit version: v0.5.1

**Comment by devhaoy** [comment]
Maybe try #684?

**Comment by MatejMecka** [comment]
@devhaoy tried it 10 times

**Comment by ccruson** [comment]
That triggers.js file looks invalid is that the full text?
Have you tried something like this:

```
var triggers = {
  search: [ "get a girlfriend","get a boyfriend","get a date", "get a prom"],
  info : ["help", "info", "commands", "instructions"],
  love : ["do you like me", "do you love me", "will you be my valentines", "can i marry you", "will you marry me"]
};

module.exports = triggers;
```
Also regarding the exit. do you have `config.admin` defined somewhere?

**Comment by MatejMecka** [comment]
@ccruson `config.admin` is defined in the `config.js` file. I just tested your method and it worked. Thanks mate :D Idk why it didn't work in the first one cause i used module.exports directly into the files but this works too. Thanks again

**Comment by peterswimm** [comment]
Closed as resolved, if not please let us know!
