### ISSUE TITLE
botkit spawns multiple instances on Stale connection disconnect, retry.

### ISSUE THREAD

**Issue by ashubham** [howdyai/botkit#750]
```javascript
var controller = Botkit.slackbot({
    debug: false,
    retry: true
});
```
[2017-04-04 11:13:09.002] [ERROR] bot - Error: Stale RTM connection, closing RTM
    at Timeout.pinger (/home/admin/shotbot/node_modules/botkit/lib/Slackbot_worker.js:182:35)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
Error: Stale RTM connection, closing RTM
    at Timeout.pinger (/home/admin/shotbot/node_modules/botkit/lib/Slackbot_worker.js:182:35)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
info: ** API CALL: https://slack.com/api/rtm.start
info: ** API CALL: https://slack.com/api/rtm.start
notice: ** BOT ID: spot ...attempting to connect to RTM!
notice: RTM websocket opened
notice: ** BOT ID: spot ...attempting to connect to RTM!
notice: ** BOT ID: spot ...reconnect attempt #1 of true being made after 1000ms
info: ** API CALL: https://slack.com/api/rtm.start
notice: RTM websocket opened
notice: ** BOT ID: spot ...attempting to connect to RTM!
notice: RTM websocket opened
error: Error: Stale RTM connection, closing RTM
[2017-04-04 11:27:45.199] [ERROR] bot - Error: Stale RTM connection, closing RTM
    at Timeout.pinger (/home/admin/shotbot/node_modules/botkit/lib/Slackbot_worker.js:182:35)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
Error: Stale RTM connection, closing RTM
    at Timeout.pinger (/home/admin/shotbot/node_modules/botkit/lib/Slackbot_worker.js:182:35)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
info: ** API CALL: https://slack.com/api/rtm.start
info: ** API CALL: https://slack.com/api/rtm.start
notice: ** BOT ID: spot ...attempting to connect to RTM!
notice: ** BOT ID: spot ...attempting to connect to RTM!
notice: RTM websocket opened
notice: RTM websocket opened
notice: ** BOT ID: spot ...reconnect attempt #1 of true being made after 1000ms
info: ** API CALL: https://slack.com/api/rtm.start
notice: ** BOT ID: spot ...attempting to connect to RTM!
notice: RTM websocket opened
error: Error: Stale RTM connection, closing RTM
notice: ** BOT ID: spot ...reconnect attempt #1 of true being made after 1000ms
info: ** API CALL: https://slack.com/api/rtm.start
notice: ** BOT ID: spot ...attempting to connect to RTM!
notice: RTM websocket opened
```

As we can see from the example above botkit tries to reconnect twice for each disconnection. Thus after two disconnections in the above case I get 3 instances of the bot running. Each replying to incoming messages.

**Comment by PrajaktaNaik** [comment]
Is there any resolution for this. I too see the same
