### ISSUE TITLE
slack teams lookup > 20 times/second?

### ISSUE THREAD

**Issue by monte-hayward** [howdyai/botkit#847]
I have a single-team bot. Currently, I'm the only one using it, and I'm not doing any automated or load testing.

Given the limited use, I would expect botkit to do something like this:
- validate team
- validate incoming user
- conduct conversation

Somehow it's triggering slack teams lookup > 20 times/second?
I realize that I'm on a tiny "free" db plan and will need to upgrade. 
However, isn't this level of teams lookup excessive?
Is there a way to stop this behavior?

```
error: Could not load team while processing webhook:  { Error: You've exceeded your current limit of 20 requests per second for lookup class. Please try later.
    at Request._callback (/path/to/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/path/to/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/path/to/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/path/to/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'Error',
  error: 'too_many_requests',
  reason: 'You\'ve exceeded your current limit of 20 requests per second for lookup class. Please try later.',
  class: 'lookup',
  rate: 20,
  scope: 'couch',
  statusCode: 429,
  request: 
   { method: 'GET',
     headers: 
      { 'content-type': 'application/json',
        accept: 'application/json' },
     uri: 'https://XXXXXX:XXXXXX@********-****-****-********-bluemix.cloudant.com/mms-slack/teams%2XY04PDQT2Z' },
  headers: 
   { 'content-type': 'application/json',
     connection: 'close',
     'x-content-type-options': 'nosniff',
     'x-cloudant-backend': 'bm-cc-dal-01',
     via: '1.1 lb1.bm-cc-dal-01 (Glum/1.34.0)',
     'strict-transport-security': 'max-age=31536000',
     statusCode: 429,
     uri: 'https://XXXXXX:XXXXXX@********-****-****-********-bluemix.cloudant.com/mms-slack/teams%2XY04PDQT2Z' },
  errid: 'non_200',
  description: 'couch returned 429' }
```

**Comment by benbrown** [comment]
Botkit looks up your team for every incoming message in order to connect that message to the right instance of the bot. It would definitely be nice to cache this info, or change the way it works in a single team instance, which are more common these days.

**Comment by monte-hayward** [comment]
> nice to cache this info, or change the way it works in a 
> single team instance, which are more common these days.
Hi @benbrown would this require code changes to `howdyai/botkit`? 
Whereabouts?

**Comment by jonchurch** [comment]
Are you hitting this limit from DB calls or API calls?
