### ISSUE TITLE
Facebook postback error

### ISSUE THREAD

**Issue by adrienbarreau** [howdyai/botkit#990]
I get this error on receiving a postback (botkit@0.5.8).

[Facebook.js:267](https://github.com/howdyai/botkit/blob/fac122b6e9ab7fef1b0eaf4e7b1855a16523e059/lib/Facebook.js#L267)

`TypeError: Cannot read property 'length' of undefined
    at Object.Facebookbot.facebook_botkit.handleWebhookPayload (/www/node_modules/botkit/lib/Facebook.js:267:59)
    at /www/node_modules/botkit/lib/Facebook.js:242:29
    at Layer.handle [as handle_request] (/www/node_modules/botkit/node_modules/express/lib/router/layer.js:95:5)
    at next (/www/node_modules/botkit/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/www/node_modules/botkit/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/www/node_modules/botkit/node_modules/express/lib/router/layer.js:95:5)
    at /www/node_modules/botkit/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/www/node_modules/botkit/node_modules/express/lib/router/index.js:335:12)
    at next (/www/node_modules/botkit/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/www/node_modules/botkit/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/www/node_modules/botkit/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/node_modules/botkit/node_modules/express/lib/router/index.js:317:13)
    at /www/node_modules/botkit/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/www/node_modules/botkit/node_modules/express/lib/router/index.js:335:12)
    at next (/www/node_modules/botkit/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/www/node_modules/body-parser/lib/types/urlencoded.js:82:7)`

**Comment by ouadie-lahdioui** [comment]
Are you using the new FB handover protocol API, are yous subscribed to the standby or messaging_handovers fields ?

Take a look at this issue #962

**Comment by adrienbarreau** [comment]
No I'm not using FB handover protocol API and I subscribed to every fields...

![messaging](https://user-images.githubusercontent.com/5724782/30157869-b44b09fc-93c3-11e7-80f1-2f86c5f98e6e.png)

**Comment by ouadie-lahdioui** [comment]
That's it, it's the same reason behind this one #962 also. try to unsubscribe from standby and messaging_handovers channels if you don't want to use the new handover API.
 
Lets me know if it worked for you !

**Comment by adrienbarreau** [comment]
Thanks @ouadie-lahdioui. It works when unsubscribe from messaging_handovers and standby.

**Comment by ouadie-lahdioui** [comment]
Good :wink:

@peterswimm can you close this one ?
